# Generated by Django 4.1.7 on 2023-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_being_held',
            field=models.BooleanField(default=False),
        ),
    ]
