# Generated by Django 4.1.7 on 2023-05-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='s3key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recordinglog',
            name='s3key',
            field=models.CharField(max_length=200),
        ),
    ]
