# Generated by Django 4.1.7 on 2023-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_crowd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initial_coordinate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
