# Generated by Django 4.0.5 on 2023-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneinfo',
            name='altitude',
            field=models.FloatField(default=0),
        ),
    ]
