# Generated by Django 4.1.7 on 2023-05-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_recordinglog_alertlog'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('coordinate', models.JSONField()),
                ('voltage', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
