# Generated by Django 4.0.5 on 2023-05-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_droneinfo_altitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headcount',
            options={'get_latest_by': ['update_time'], 'ordering': ['id']},
        ),
    ]
